"use client";

import { LanguageSwitcher } from "./LanguageSwitcher";
import { localizedPath, type Locale, type RouteKey } from "./config";
import { WhatsAppButton } from "../WhatsAppButton";

const pageCopy: Record<Locale, Record<RouteKey, { eyebrow: string; heading: string; body: string; cta: string }>> = {
  fr: { home: { eyebrow: "SOLUTIONS PVC INDUSTRIELLES", heading: "Des matériaux fiables pour les projets exigeants.", body: "Tissus PVC, bâches et solutions OEM/ODM pour la construction, le transport et les applications temporaires.", cta: "Demander un devis" }, product: { eyebrow: "SÉRIE DE MATÉRIAUX", heading: "Tissus PVC industriels", body: "Des bâches PVC et EVA résistantes, adaptées aux importateurs, distributeurs et projets internationaux.", cta: "Parler de votre projet" }, productList: { eyebrow: "GAMME DE PRODUITS", heading: "Nos catégories de produits", body: "Tissus enduits, bâches, barrières acoustiques et couvertures industrielles sur mesure.", cta: "Voir les produits" }, blogList: { eyebrow: "CONSEILS SUPFIELD", heading: "Blog et articles", body: "Guides pratiques sur le choix, la spécification et l'approvisionnement des matériaux PVC.", cta: "Lire les guides" }, blogSingle: { eyebrow: "GUIDE D'ACHAT", heading: "Comment choisir un tissu PVC", body: "Définissez l'application, les conditions d'utilisation et les exigences techniques avant votre commande.", cta: "Retour au blog" }, contact: { eyebrow: "CONTACT SUPFIELD", heading: "Parlons de votre prochaine solution matière.", body: "Envoyez votre application, vos dimensions, vos quantités et votre pays de livraison à notre équipe export.", cta: "Contacter Alan" }, inquiry: { eyebrow: "DEMANDE B2B", heading: "Parlez-nous de votre projet.", body: "Partagez les détails essentiels et notre équipe vous aidera à définir la bonne spécification.", cta: "Envoyer la demande" }, soundproofBarrier: { eyebrow: "CONTRÔLE DU BRUIT", heading: "Barrières acoustiques PVC", body: "Solutions durables et personnalisables pour chantiers, zones industrielles et infrastructures.", cta: "Demander une cotation" } },
  es: { home: { eyebrow: "SOLUCIONES DE PVC INDUSTRIAL", heading: "Materiales fiables para proyectos exigentes.", body: "Tejidos PVC, lonas y soluciones OEM/ODM para construcción, transporte y aplicaciones temporales.", cta: "Solicitar cotización" }, product: { eyebrow: "SERIE DE MATERIALES", heading: "Tejidos PVC industriales", body: "Lonas PVC y EVA resistentes para importadores, distribuidores y proyectos globales.", cta: "Hablemos de su proyecto" }, productList: { eyebrow: "GAMA DE PRODUCTOS", heading: "Nuestras categorías de productos", body: "Tejidos recubiertos, lonas, barreras acústicas y cubiertas industriales a medida.", cta: "Ver productos" }, blogList: { eyebrow: "CONOCIMIENTOS SUPFIELD", heading: "Blog y artículos", body: "Guías prácticas sobre selección, especificación y compra de materiales PVC.", cta: "Leer guías" }, blogSingle: { eyebrow: "GUÍA DE COMPRA", heading: "Cómo elegir tejido PVC", body: "Defina la aplicación, las condiciones de uso y los requisitos técnicos antes de realizar su pedido.", cta: "Volver al blog" }, contact: { eyebrow: "CONTACTO SUPFIELD", heading: "Hablemos de su próxima solución de material.", body: "Envíe a nuestro equipo de exportación su aplicación, dimensiones, cantidades y país de entrega.", cta: "Contactar a Alan" }, inquiry: { eyebrow: "CONSULTA B2B", heading: "Cuéntenos sobre su proyecto.", body: "Comparta los detalles esenciales y nuestro equipo le ayudará a definir la especificación adecuada.", cta: "Enviar consulta" }, soundproofBarrier: { eyebrow: "CONTROL DE RUIDO", heading: "Barreras acústicas de PVC", body: "Soluciones duraderas y personalizables para obras, zonas industriales e infraestructura.", cta: "Solicitar cotización" } },
  ja: { home: { eyebrow: "産業用PVCソリューション", heading: "要求の厳しいプロジェクトのための信頼できる材料。", body: "建設、輸送、仮設用途向けのPVC生地、ターポリン、OEM/ODMソリューション。", cta: "見積もりを依頼" }, product: { eyebrow: "マテリアルシリーズ", heading: "産業用PVC生地", body: "輸入業者、販売代理店、国際プロジェクト向けの耐久性あるPVC・EVAターポリン。", cta: "プロジェクトを相談" }, productList: { eyebrow: "製品ライン", heading: "製品カテゴリー", body: "コーティング生地、ターポリン、防音バリア、特注産業カバー。", cta: "製品を見る" }, blogList: { eyebrow: "SUPFIELD INSIGHTS", heading: "ブログ・記事", body: "PVC材料の選定、仕様、調達に関する実践ガイド。", cta: "ガイドを読む" }, blogSingle: { eyebrow: "調達ガイド", heading: "PVC生地の選び方", body: "注文前に用途、使用環境、技術要件を明確にしてください。", cta: "ブログに戻る" }, contact: { eyebrow: "SUPFIELDに連絡", heading: "次の材料ソリューションについてご相談ください。", body: "用途、寸法、数量、納入国を輸出チームにお送りください。", cta: "Alanに連絡" }, inquiry: { eyebrow: "B2Bお問い合わせ", heading: "プロジェクトについて教えてください。", body: "必要事項を共有いただければ、適切な仕様作成を支援します。", cta: "問い合わせを送信" }, soundproofBarrier: { eyebrow: "騒音対策", heading: "PVC防音バリア", body: "建設現場、工業地帯、インフラ向けの耐久性・カスタマイズ性の高いソリューション。", cta: "見積もりを依頼" } },
  de: { home: { eyebrow: "INDUSTRIELLE PVC-LÖSUNGEN", heading: "Zuverlässige Materialien für anspruchsvolle Projekte.", body: "PVC-Gewebe, Planen und OEM/ODM-Lösungen für Bau, Transport und temporäre Anwendungen.", cta: "Angebot anfordern" }, product: { eyebrow: "MATERIALSERIE", heading: "Industrielle PVC-Gewebe", body: "Robuste PVC- und EVA-Planen für Importeure, Händler und globale Projekte.", cta: "Projekt besprechen" }, productList: { eyebrow: "PRODUKTPORTFOLIO", heading: "Unsere Produktkategorien", body: "Beschichtete Gewebe, Planen, Schallschutzbarrieren und kundenspezifische Industrieabdeckungen.", cta: "Produkte ansehen" }, blogList: { eyebrow: "SUPFIELD INSIGHTS", heading: "Blog und Artikel", body: "Praxisleitfäden zur Auswahl, Spezifikation und Beschaffung von PVC-Materialien.", cta: "Leitfäden lesen" }, blogSingle: { eyebrow: "BESCHAFFUNGSLEITFADEN", heading: "PVC-Gewebe auswählen", body: "Definieren Sie Anwendung, Einsatzbedingungen und technische Anforderungen vor der Bestellung.", cta: "Zum Blog zurück" }, contact: { eyebrow: "SUPFIELD KONTAKT", heading: "Sprechen wir über Ihre nächste Materiallösung.", body: "Senden Sie Anwendung, Abmessungen, Mengen und Lieferland an unser Exportteam.", cta: "Alan kontaktieren" }, inquiry: { eyebrow: "B2B-ANFRAGE", heading: "Erzählen Sie uns von Ihrem Projekt.", body: "Teilen Sie die wichtigsten Details, damit unser Team die passende Spezifikation definieren kann.", cta: "Anfrage senden" }, soundproofBarrier: { eyebrow: "LÄRMSCHUTZ", heading: "PVC-Schallschutzbarrieren", body: "Langlebige, anpassbare Lösungen für Baustellen, Industriegebiete und Infrastruktur.", cta: "Angebot anfordern" } },
  en: {} as Record<RouteKey, { eyebrow: string; heading: string; body: string; cta: string }>,
};

export function LocalizedPage({ locale, routeKey }: { locale: Locale; routeKey: RouteKey }) {
  const copy = pageCopy[locale][routeKey];
  const productRoute = localizedPath(locale, "product");
  const inquiryRoute = localizedPath(locale, "inquiry");
  const homeRoute = localizedPath(locale, "home");
  return <main lang={locale} className="min-h-screen bg-slate-950 text-white"><header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><a href={homeRoute} className="font-bold tracking-[.16em]">SUPFIELD</a><nav className="hidden gap-6 text-sm md:flex"><a href={productRoute}>Products</a><a href={localizedPath(locale, "blogList")}>Insights</a><a href={localizedPath(locale, "contact")}>Contact</a></nav><LanguageSwitcher activeLocale={locale} pathname={`/${locale}${localizedPath(locale, routeKey) === "/" ? "" : localizedPath(locale, routeKey)}`} /></header><section className="mx-auto grid min-h-[72vh] max-w-7xl items-center gap-10 px-6 py-20 md:grid-cols-[1.2fr_.8fr]"><div><p className="mb-5 text-xs font-bold tracking-[.2em] text-cyan-300">{copy.eyebrow}</p><h1 className="max-w-4xl text-5xl font-black tracking-tight md:text-7xl">{copy.heading}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">{copy.body}</p><a href={routeKey === "blogSingle" ? localizedPath(locale, "blogList") : inquiryRoute} className="mt-9 inline-flex bg-yellow-400 px-6 py-4 font-bold text-slate-950 transition hover:bg-yellow-300">{copy.cta}</a></div><aside className="border border-cyan-400/25 bg-slate-900/70 p-7"><p className="text-sm font-bold text-cyan-300">SUPFIELD TECHNOLOGY</p><dl className="mt-6 space-y-5 text-sm"><div><dt className="text-slate-400">OEM / ODM</dt><dd className="mt-1 font-semibold">PVC & EVA Industrial Materials</dd></div><div><dt className="text-slate-400">Export Support</dt><dd className="mt-1 font-semibold">Global Importers & Distributors</dd></div><div><dt className="text-slate-400">Email</dt><dd className="mt-1 font-semibold">li18061128988@gmail.com</dd></div></dl></aside></section><section className="border-t border-white/10 bg-slate-900 px-6 py-12"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-3"><article><h2 className="text-xl font-bold">PVC Coated Fabrics</h2><p className="mt-3 text-slate-300">Durable coated materials for industrial covers and structures.</p></article><article><h2 className="text-xl font-bold">Custom Fabrication</h2><p className="mt-3 text-slate-300">Dimensions, colours, finishing and packaging tailored to project needs.</p></article><article><h2 className="text-xl font-bold">Project Enquiry</h2><p className="mt-3 text-slate-300">Share application, quantity and delivery market for a relevant quotation.</p></article></div></section><WhatsAppButton /></main>;
}
