import { ArrowRight, CheckCircle, Cube, GlobeSimple, ShieldCheck } from "@phosphor-icons/react";

const advantages = [[ShieldCheck, "High-strength materials", "PVC and EVA tarpaulin options designed for demanding project conditions."], [Cube, "OEM / ODM support", "Discuss dimensions, colors, finishes and project-specific construction."], [GlobeSimple, "Global B2B supply", "Built for importers, distributors and project buyers across international markets."]];
const specs = [["Material options", "PVC and EVA tarpaulins"], ["Core uses", "Construction, transportation and temporary projects"], ["Customization", "Size, color, finishing and project requirement"], ["Commercial model", "OEM / ODM and export supply"]];
const applications = [["Construction protection", "Covers and protective materials for active building sites.", "/assets/soundproof-product.jpg"], ["Transportation covers", "Durable material options for cargo and vehicle cover projects.", "/assets/pvc-product.jpg"], ["Temporary engineering", "Flexible materials for temporary structures and outdoor work zones.", "/assets/geocell-product.jpg"]];

export function ProductPage() {
  return <main className="pvc-product-page">
    <header className="pvc-header"><a className="pvc-brand" href="/"><img src="/assets/ept-logo.png" alt="EPT Supfield Technology" /><span>SUPFIELD<br />TECHNOLOGY</span></a><nav><a href="/">Home</a><a href="/product-list">Products</a><a href="/contact">Contact</a></nav><a className="pvc-header-cta" href="/inquiry">Get a Quote <ArrowRight size={16} /></a></header>
    <section className="pvc-hero"><div className="pvc-hero-photo" style={{ backgroundImage: "linear-gradient(90deg, rgba(7,16,23,.9), rgba(7,16,23,.62) 46%, rgba(7,16,23,.1)), url('/assets/hero-factory.jpg')" }} /><div className="pvc-hero-copy"><p>INDUSTRIAL MATERIAL SERIES</p><h1>Industrial PVC Fabrics</h1><h2>Built for Demanding Projects.</h2><span className="pvc-hero-line" /><strong>PVC & EVA TARPAULINS</strong></div></section>
    <section className="pvc-intro"><div><p className="pvc-eyebrow">PRODUCT OVERVIEW</p><h2>Reliable coverage for work that cannot wait.</h2></div><div><p>High-strength PVC and EVA tarpaulins for construction, transportation and temporary engineering applications. We support OEM and ODM requirements for global importers and distributors.</p><div className="pvc-intro-points"><span><CheckCircle size={17} weight="fill" /> Project-oriented material support</span><span><CheckCircle size={17} weight="fill" /> Export enquiry coordination</span></div></div></section>
    <section className="pvc-advantages"><div className="pvc-wrap"><p className="pvc-eyebrow">PRODUCT ADVANTAGES</p><h2>Make the material work for the project.</h2><div className="pvc-advantage-grid">{advantages.map(([Icon, title, copy]) => <article key={title}><Icon size={29} weight="light" /><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="pvc-specification"><div className="pvc-spec-photo" style={{ backgroundImage: "url('/assets/pvc-product.jpg')" }} /><div className="pvc-spec-copy"><p className="pvc-eyebrow">SPECIFICATIONS</p><h2>Start with the requirement, then define the material.</h2><dl>{specs.map(([term, detail]) => <div key={term}><dt>{term}</dt><dd>{detail}</dd></div>)}</dl></div></section>
    <section className="pvc-applications"><div className="pvc-wrap"><div className="pvc-section-heading"><div><p className="pvc-eyebrow">APPLICATIONS</p><h2>Where industrial tarpaulins fit.</h2></div><a href="/inquiry">Discuss your use case <ArrowRight size={17} /></a></div><div className="pvc-application-grid">{applications.map(([title, copy, image], index) => <article key={title}><div className="pvc-application-image" style={{ backgroundImage: `linear-gradient(0deg, rgba(5,13,18,.63), rgba(5,13,18,.02)), url(${image})` }}><span>0{index + 1}</span></div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="pvc-bottom-cta"><div><p>SUPFIELD TECHNOLOGY / B2B PROJECT ENQUIRIES</p><h2>Ready to define your material requirement?</h2></div><div><a className="pvc-quote-action" href="/inquiry">Get a Quote <ArrowRight size={18} /></a><a className="pvc-products-action" href="/product-list">View Products <ArrowRight size={18} /></a></div></section>
    <footer className="pvc-footer"><a className="pvc-brand" href="/"><img src="/assets/ept-logo.png" alt="EPT Supfield Technology" /><span>SUPFIELD<br />TECHNOLOGY</span></a><span>Industrial PVC materials for global project supply.</span><a href="mailto:li18061128988@gmail.com">li18061128988@gmail.com</a></footer>
  </main>;
}
